mybatis:
  type-aliases-package: com.forum.entity
  mapper-locations: classpath:mapper/*.xml

server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/cusb_forum?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: yanhanwen
    driver-class-name: com.mysql.jdbc.Driver
  aop:
    auto: true
    proxy-target-class: true
#  redis:
#    database: 0
#    host: 127.0.0.1
#    port: 6379
#    timeout: 10000
#    pool:
#      max-active: 8
#      max-idle: 8
#      min-idle: 1
#      max-wait: -1

# LOGGING
logging:
    config: classpath:logback.xml